default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  username: developer
  password: "vidya@psql"

development:
  <<: *default
  database: orbit_development

test:
  <<: *default
  database: orbit_test

production:
  primary:
    <<: *default
    database: orbit_production