class Task < ApplicationRecord
  belongs_to :project
  belongs_to :user
  has_many :comments, dependent: :destroy

  enum :priority, { high: "high", medium: "medium", low: "low" }, default: :medium
  enum :status, { pending: "pending", in_progress: "in_progress", completed: "completed" }, default: :pending

  validates :title, presence: true
  validates :description, presence: true
  validates :due_date, presence: true
  validate :due_date_cannot_be_in_the_past

  # Scopes
  # Note: pending, completed, in_progress are auto-generated by enum
  scope :overdue,       -> { where("due_date < ?", Date.current).where.not(status: "completed") }
  scope :due_today,     -> { where(due_date: Date.current) }
  scope :high_priority, -> { where(priority: "high") }

  # Model Methods
  # Note: completed? is auto-generated by enum

  def overdue?
    due_date.present? && due_date < Date.today && !completed?
  end

  def mark_complete
    update(status: "completed")  # persists to the DB immediately
  end

  def display_status
    status.humanize  # returns "Pending", "In progress", "Completed"
  end

  # Class Methods
  def self.completed_percentage
    return 0 if count.zero?
    (completed.count.to_f / count * 100).round(2)
  end

  private

  def due_date_cannot_be_in_the_past
    if due_date.present? && due_date < Date.today
      errors.add(:due_date, "can't be in the past")
    end
  end
end
